# Hyprland window manager configuration
# Consumes shared keybinding data from keybindings.nix
# Keeps Hyprland-specific settings (monitor, decoration, animation, input, etc.)
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.hyprland-desktop;
  theme = config.theme.tokyoNight;
  inherit (pkgs.stdenv) isLinux;
in {
  options.programs.hyprland-desktop.generatedBinds = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    default = [];
    description = "Keybind lines generated by the shared keybindings module";
  };

  options.programs.hyprland-desktop.lockOnStart =
    lib.mkEnableOption "locking the session immediately on Hyprland startup via `hyprlock --grace 0`";

  config = lib.mkIf (cfg.enable && isLinux) {
    wayland.windowManager.hyprland = {
      enable = true;
      configType = "hyprlang";
      settings = {
        "$mod" = "SUPER";

        # Monitor config - dual Dell U3824DW ultrawides (stacked)
        # DP-2 on top, DP-1 on bottom
        monitor = [
          "DP-2,3840x1600@60,0x0,1"
          "DP-1,3840x1600@60,0x1600,1"
        ];

        # General settings
        general = {
          gaps_in = 2;
          gaps_out = 4;
          border_size = 2;
          "col.active_border" = "rgb(${lib.removePrefix "#" theme.borderActive})";
          "col.inactive_border" = "rgb(${lib.removePrefix "#" theme.border})";
          layout = "dwindle";
        };

        # Decorations (blur, rounding)
        decoration = {
          # Just enough to take the hard pixel off the corner. 8 read as dated;
          # 0 makes the blur edge look like a rendering artefact where a window
          # meets the wallpaper, so this stops short of square.
          rounding = 2;
          blur = {
            enabled = true;
            size = 8;
            passes = 2;
            new_optimizations = true;
          };
          shadow = {
            enabled = true;
            range = 8;
            render_power = 2;
          };
        };

        # Subtle animations
        animations = {
          enabled = true;
          bezier = "ease, 0.25, 0.1, 0.25, 1";
          animation = [
            "windows, 1, 3, ease, slide"
            "windowsOut, 1, 3, ease, slide"
            "fade, 1, 3, ease"
            "workspaces, 1, 3, ease, slide"
          ];
        };

        # Input
        input = {
          kb_layout = "us";
          kb_options = "caps:escape";
          numlock_by_default = true;
          repeat_rate = 50;
          repeat_delay = 300;
          follow_mouse = 1;
          sensitivity = 0;
        };

        # Three-finger horizontal swipe moves between workspaces, like macOS.
        #
        # Hyprland 0.51 replaced the old `gestures { workspace_swipe = true; }`
        # block with this unified keyword, so on 0.55 neither
        # `gestures:workspace_swipe` nor `gesture` exists as an option any more
        # (`hyprctl getoption` reports "no such option" for both) -- the syntax
        # is `<fingers>, <direction>, <action>`. No-op on a desktop with no
        # touchpad.
        gesture = ["3, horizontal, workspace"];

        # Dwindle layout
        dwindle = {
          preserve_split = true;
        };

        # Keybindings (from shared keybindings module)
        bind = cfg.generatedBinds;

        # Mouse bindings
        bindm = [
          "$mod, mouse:272, movewindow"
          "$mod, mouse:273, resizewindow"
        ];

        # Window rules. Current Hyprland syntax: `match:<selector>, <rule> <value>`
        # (this replaced the deprecated windowrulev2 `<rule>, class:...` form).
        windowrule = [
          "match:class ^(pavucontrol)$, float on"
          "match:class ^(pavucontrol)$, size 600 400"
          "match:class ^(pavucontrol)$, move 100%-620 50"
          # waybar's network module opens these; float them by the tray like
          # pavucontrol rather than letting them tile.
          "match:class ^(network-tui|nm-connection-editor)$, float on"
          "match:class ^(network-tui|nm-connection-editor)$, size 700 500"
          "match:class ^(network-tui|nm-connection-editor)$, move 100%-720 50"
          "match:class ^(kicad|eeschema|pcbnew|gerbview|pl_editor|bitmap2component|pcb_calculator)$, float on"
        ];

        # Autostart
        exec-once =
          lib.optional cfg.lockOnStart "hyprlock --grace 0"
          ++ [
            # NOTE: waybar is deliberately absent. waybar.nix enables Home
            # Manager's systemd user service, which orders it after
            # graphical-session.target and restarts it on failure. Listing it
            # here as well starts a second, untracked instance the moment
            # anything touches the unit (e.g. `systemctl --user restart
            # waybar`), leaving two bars stacked on the screen.
            "hyprpaper"
            "mako"
            "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1"
            "wl-paste --type text --watch cliphist store"
            "wl-paste --type image --watch cliphist store"
          ];
      };
    };
  };
}
