# Hyprland window manager configuration
# Consumes shared keybinding data from keybindings.nix
# Keeps Hyprland-specific settings (monitor, decoration, animation, input, etc.)
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.programs.hyprland-desktop;
  theme = config.theme.tokyoNight;
  inherit (pkgs.stdenv) isLinux;
in {
  options.programs.hyprland-desktop.generatedBinds = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    default = [];
    description = "Keybind lines generated by the shared keybindings module";
  };

  config = lib.mkIf (cfg.enable && isLinux) {
    wayland.windowManager.hyprland = {
      enable = true;
      settings = {
        "$mod" = "SUPER";

        # Monitor config - dual Dell U3824DW ultrawides (stacked)
        # DP-2 on top, DP-1 on bottom
        monitor = [
          "DP-2,3840x1600@60,0x0,1"
          "DP-1,3840x1600@60,0x1600,1"
        ];

        # General settings
        general = {
          gaps_in = 2;
          gaps_out = 4;
          border_size = 2;
          "col.active_border" = "rgb(${lib.removePrefix "#" theme.borderActive})";
          "col.inactive_border" = "rgb(${lib.removePrefix "#" theme.border})";
          layout = "dwindle";
        };

        # Decorations (blur, rounding)
        decoration = {
          rounding = 8;
          blur = {
            enabled = true;
            size = 8;
            passes = 2;
            new_optimizations = true;
          };
          shadow = {
            enabled = true;
            range = 8;
            render_power = 2;
          };
        };

        # Subtle animations
        animations = {
          enabled = true;
          bezier = "ease, 0.25, 0.1, 0.25, 1";
          animation = [
            "windows, 1, 3, ease, slide"
            "windowsOut, 1, 3, ease, slide"
            "fade, 1, 3, ease"
            "workspaces, 1, 3, ease, slide"
          ];
        };

        # Input
        input = {
          kb_layout = "us";
          kb_options = "caps:escape";
          numlock_by_default = true;
          repeat_rate = 50;
          repeat_delay = 300;
          follow_mouse = 1;
          sensitivity = 0;
        };

        # Dwindle layout
        dwindle = {
          pseudotile = true;
          preserve_split = true;
        };

        # Keybindings (from shared keybindings module)
        bind = cfg.generatedBinds;

        # Mouse bindings
        bindm = [
          "$mod, mouse:272, movewindow"
          "$mod, mouse:273, resizewindow"
        ];

        # Window rules
        windowrulev2 = [
          "float, class:^(pavucontrol)$"
          "size 600 400, class:^(pavucontrol)$"
          "move 100%-620 50, class:^(pavucontrol)$"
          "float, class:^(kicad|eeschema|pcbnew|gerbview|pl_editor|bitmap2component|pcb_calculator)$"
        ];

        # Autostart
        exec-once = [
          "waybar"
          "hyprpaper"
          "mako"
          "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1"
          "wl-paste --type text --watch cliphist store"
          "wl-paste --type image --watch cliphist store"
        ];
      };
    };
  };
}
