# `vivado-install` — scripts the one-time, outside-nix install onto /persist.
#
# Encapsulates what would otherwise be manual steps: extract the AMD tarball,
# fix its `/bin/bash` shebangs (NixOS has none), run the vendor `xsetup` batch
# installer under the host's nix-ld, selecting only the device modules chosen
# here. The install OPTIONS live in ./options.nix as Nix data and are exposed
# as overridable args, e.g.:
#
#   nix run .#vivado-install                       # defaults (58G family)
#   nix run '.#vivado-install.override { enabledModules = [ "Kintex-7 FPGAs" ]; }'
#
# Requires `programs.nix-ld.enable = true` on the host (already set on desktop).
# Produces an installed tree at $VIVADO_DEST which default.nix then imports
# into the store (see README).
{
  lib,
  pkgs,
  writeShellApplication,
  bash,
  gnutar,
  coreutils,
  gnused,
  gawk,
  findutils,
  which,
  util-linux,
  procps,
  glibc,
  # Options (override to change the install) --------------------------------
  # Default to Enterprise: the free Standard edition installs Virtex UltraScale+
  # devices (e.g. xcux35 / Alveo X3522) as NON-TIMING — synthesis works but
  # implementation dies with "Cannot run timing on a non-timing device". The
  # Enterprise edition ships the timing/speed data (verified: 58G family data
  # 338M -> 1015M), enabling full synth->P&R->bitstream. No paid .lic is needed;
  # the built-in entitlement covers it (a full fpga_X3522 bitstream was built
  # this way). Override to "Vivado ML Standard" only for 7-series/small parts.
  edition ? "Vivado ML Enterprise",
  enabledModules ? null, # null -> options.nix default
}: let
  opts = import ./options.nix;
  fhsLibs = import ./fhs-libs.nix pkgs;
  ldLibraryPath = lib.makeLibraryPath fhsLibs;

  selected =
    if enabledModules == null
    then opts.defaultEnabledModules
    else enabledModules;

  # Validate selections against the catalog so a typo fails at eval, not mid-install.
  bad = lib.subtractLists opts.allModules selected;
  _ =
    lib.throwIf (bad != [])
    "vivado-install: unknown module(s) ${lib.concatStringsSep ", " (map (m: ''"${m}"'') bad)}; see options.nix allModules"
    null;

  modulesLine =
    lib.concatStringsSep ","
    (map (m: "${m}:${
        if lib.elem m selected
        then "1"
        else "0"
      }")
      opts.allModules);
in
  writeShellApplication {
    name = "vivado-install";
    runtimeInputs = [bash gnutar coreutils gnused gawk findutils which util-linux procps];
    text = ''
      # --- config (override via env) -----------------------------------------
      installer_tar="''${VIVADO_INSTALLER_TAR:-/persist/software/vivado.${opts.version}.tar}"
      workdir="''${VIVADO_WORKDIR:-/persist/tmp/vivado-extract}"
      # Install straight to the stable location default.nix wraps. Vivado bakes
      # this absolute path into its settings scripts, so DON'T install elsewhere
      # and move — install where it will live (override must match installRoot).
      dest="''${VIVADO_DEST:-/persist/xilinx}"
      pack_tar="''${VIVADO_PACK_TAR:-}"   # if set, tar the install to this path
      setupdir="$workdir/${opts.installerDir}"

      echo ">> vivado-install ${opts.version} — edition '${edition}'"
      echo ">> modules enabled: ${lib.concatStringsSep ", " selected}"

      if [ ! -f "$installer_tar" ]; then
        echo "ERROR: installer tar not found: $installer_tar" >&2
        echo "       set VIVADO_INSTALLER_TAR to the AMD unified installer (.tar)." >&2
        exit 1
      fi

      # --- extract -----------------------------------------------------------
      # Payload (95 GB) is expensive: extract only if missing.
      if [ ! -d "$setupdir/payload" ] || [ -z "$(ls -A "$setupdir/payload" 2>/dev/null)" ]; then
        echo ">> extracting full installer (incl. payload) to $workdir ..."
        mkdir -p "$workdir"
        tar xf "$installer_tar" -C "$workdir"
      fi
      # Always refresh the front-end scripts from the tar so shebang patching
      # starts from pristine "#! /bin/bash" lines — makes re-runs idempotent and
      # wipes any prior mis-patch. Cheap (~1.3 GB), leaves payload untouched.
      echo ">> refreshing installer front-end (excluding payload) ..."
      tar xf "$installer_tar" -C "$workdir" --exclude='*/payload/*'

      # --- patch /bin/bash shebangs (NixOS has none) -------------------------
      # Anchored to the shebang only ("#!" + optional spaces + /bin/bash), so it
      # never matches a /bin/bash substring inside an already-substituted store
      # path. Scope excludes payload/ (95 GB of .xz).
      echo ">> patching /bin/bash shebangs"
      while IFS= read -r f; do
        sed -i '1s|^#! */bin/bash|#!${bash}/bin/bash|' "$f"
      done < <(grep -rl --exclude-dir=payload '/bin/bash' "$setupdir" 2>/dev/null || true)

      # --- generate install config from nix options --------------------------
      cfg="$workdir/install_config.txt"
      cat > "$cfg" <<EOF
      #### Generated by vivado-install (nix) — edition ${edition} ####
      Edition=${edition}
      Product=Vivado
      Destination=$dest
      Modules=${modulesLine}
      InstallOptions=Acquire or Manage a License Key:0
      CreateProgramGroupShortcuts=0
      ProgramGroupFolder=AMD Adaptive SoC and FPGA Tools
      CreateShortcutsForAllUsers=0
      CreateDesktopShortcuts=0
      CreateFileAssociation=0
      EOF
      echo ">> config written to $cfg"

      # --- nix-ld environment for the vendor JRE / tools ---------------------
      # Curated set first, then the host's nix-ld default set as a proven
      # fallback for any native-lib dependency the curated list misses.
      export NIX_LD_LIBRARY_PATH="${ldLibraryPath}:/run/current-system/sw/share/nix-ld/lib"
      if [ -r /run/current-system/sw/nix-support/dynamic-linker ]; then
        NIX_LD="$(cat /run/current-system/sw/nix-support/dynamic-linker)"
      else
        NIX_LD="${glibc}/lib/ld-linux-x86-64.so.2"
      fi
      export NIX_LD
      export HOME="$workdir/home"; mkdir -p "$HOME"

      # --- run the batch install ---------------------------------------------
      # NOTE: xsetup exits 0 even when its Java installer dies, so we cannot
      # trust its return code — verify the vivado binary exists afterwards.
      echo ">> installing to $dest ..."
      if ! ( cd "$setupdir" && bash ./xsetup -a XilinxEULA,3rdPartyEULA -b Install -c "$cfg" ); then
        echo ">> (xsetup returned non-zero; verifying result anyway)"
      fi

      vivado_bin="$dest/${opts.version}/Vivado/bin/vivado"
      if [ ! -x "$vivado_bin" ]; then
        echo "ERROR: install did not produce $vivado_bin — see the installer log in" >&2
        echo "       $HOME/.Xilinx/xinstall/ (look for 'native libs' / shebang errors)." >&2
        exit 1
      fi
      echo ">> installed OK: $vivado_bin"

      # --- optional: pack the tree for `nix-store --add-fixed` ---------------
      if [ -n "$pack_tar" ]; then
        echo ">> packing installed tree to $pack_tar ..."
        tar cf "$pack_tar" -C "$dest" .
        echo ">> done. Register it in the store with:"
        echo "     nix-store --add-fixed sha256 $pack_tar"
        echo "     nix hash file $pack_tar   # put this in default.nix installedTree.sha256"
      else
        echo ">> next: re-run with VIVADO_PACK_TAR=/persist/software/vivado-${opts.version}-installed.tar to pack for the store"
      fi
    '';

    meta = with lib; {
      description = "One-time outside-nix installer for Vivado (device-limited, nix-ld driven)";
      platforms = ["x86_64-linux"];
      mainProgram = "vivado-install";
    };
  }
